apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: iqrd8fi7b-nodejs
  janus-idp.io/tekton: iqrd8fi7b-nodejs
  backstage.io/kubernetes-id: iqrd8fi7b-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: iqrd8fi7b-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
